# WorldServer 配置
[network]
internal_port = 8002
io_threads = 4

[center]
host = "127.0.0.1"
port = 7001

[database]
conn_string = "host=127.0.0.1 port=6432 dbname=massive"
worker_count = 3

[world]
id = 1
max_players = 10000
# gate_addresses = ["127.0.0.1:9001"]

[log]
level = 0
dir = "logs"
